"""
错误码常量定义模块

定义按业务模块分类的错误码常量，用于标准化API错误响应。
所有错误码采用大写蛇形命名法，格式为：模块名_错误类型
"""

# 认证模块错误码
AUTH_INVALID_CREDENTIALS = "AUTH_INVALID_CREDENTIALS"
AUTH_TOKEN_EXPIRED = "AUTH_TOKEN_EXPIRED"
AUTH_TOKEN_INVALID = "AUTH_TOKEN_INVALID"
AUTH_INSUFFICIENT_PERMISSIONS = "AUTH_INSUFFICIENT_PERMISSIONS"
AUTH_USER_NOT_FOUND = "AUTH_USER_NOT_FOUND"
AUTH_USER_DISABLED = "AUTH_USER_DISABLED"

# 案件模块错误码
CASE_NOT_FOUND = "CASE_NOT_FOUND"
CASE_ALREADY_EXISTS = "CASE_ALREADY_EXISTS"
CASE_INVALID_STATUS = "CASE_INVALID_STATUS"
CASE_OPERATION_NOT_ALLOWED = "CASE_OPERATION_NOT_ALLOWED"
CASE_DATA_VALIDATION_ERROR = "CASE_DATA_VALIDATION_ERROR"
CASE_ANALYSIS_FAILED = "CASE_ANALYSIS_FAILED"

# 工作流模块错误码
WORKFLOW_NOT_FOUND = "WORKFLOW_NOT_FOUND"
WORKFLOW_INVALID_STATE = "WORKFLOW_INVALID_STATE"
WORKFLOW_TRANSITION_ERROR = "WORKFLOW_TRANSITION_ERROR"
WORKFLOW_NODE_EXECUTION_FAILED = "WORKFLOW_NODE_EXECUTION_FAILED"
WORKFLOW_TIMEOUT = "WORKFLOW_TIMEOUT"
WORKFLOW_CONFIG_ERROR = "WORKFLOW_CONFIG_ERROR"

# 审批模块错误码
APPROVAL_NOT_FOUND = "APPROVAL_NOT_FOUND"
APPROVAL_ALREADY_PROCESSED = "APPROVAL_ALREADY_PROCESSED"
APPROVAL_INVALID_DECISION = "APPROVAL_INVALID_DECISION"
APPROVAL_PERMISSION_DENIED = "APPROVAL_PERMISSION_DENIED"
APPROVAL_WORKFLOW_ERROR = "APPROVAL_WORKFLOW_ERROR"

# 通用错误码
VALIDATION_ERROR = "VALIDATION_ERROR"
INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"
SERVICE_UNAVAILABLE = "SERVICE_UNAVAILABLE"
DATABASE_ERROR = "DATABASE_ERROR"
EXTERNAL_API_ERROR = "EXTERNAL_API_ERROR"